% Plot and return the power spectrum of a given grayscale image
% Ed Foley
% December 8, 2014, updated May 20, 2017
% Provided with zero warranty
%
% img_in: the grayscale image that is to be processed
% img_in_scale: what proportion of the original dimensions the input should
%   be resized to. Smaller factors greatly enhance speed and reduce memory
%   usage at the expense of adding resizing artifacts into the FFT.
% fft_scale: the proportion, relative to the size of the reduced image, of
%   the image the FFT will actually act on (padding with zeros as
%   necessary). Larger values are more memory-demanding but yield better
%   transform resolution.
% LD: a matrix whose columns designate a u-position, a v-position, and a
%   relative magnitude of a point of light whose diffraction effects are to
%   be shown.  Add more rows for additional points of light.
% mag_lims: the range of magnitudes that should be covered by the color
%   bar.  Values above -mag_lims(1) will be shown the same color as
%   -mag_lims(1); values below -mag_lims(2) will be shown the same color as
%   -mag_lims(2).  For example, enter [1.0 4.0] to show contrast ratios 
%   between -4.0 and -1.0.
% LD_lim: controls the u- and v-axis boundaries.  The plot will be bounded
%   by [-LD_lim, LD_lim] on both the u- and v-axes.
% nominal_plot_size: the target size of the aperture and PSF plots
% color_map: the color map to use for display. The values 'parula', 'hot'
%   and 'bone' work better than others.
% print_mode: true inverts colors in output images to reduce black ink
%   usage
% figure_num: the starting figure number to use when plotting results.
%   Because up to three plots will be produced, make sure to space
%   the figure_num arguments in successive calls by at least 3.
% mask_name: the name for the input image.  This will be shown in the plot
%   titles.
% filename_string: the string to use in the files generated by this
%   function.  Make sure to leave off extensions and use only valid
%   characters.
function [ xfm ] = show_fft_plus(img_in, img_in_scale, fft_scale, LD, mag_lims, LD_lim, nominal_plot_size, color_map, print_mode, figure_num, mask_name, filename_string)
font_size_const = 14;  % font size to use on plots
show_aperture =  true;  % true to display the aperture image in a plot window and save it in EPS and PNG format
show_simple =    true;  % true display a grayscale power spectrum with no axis labels and save a PNG of it
show_scaled =    true;  % true to display the formatted power spectrum with axis labels and save it in EPS and PNG format
make_spec_file = true;  % true to create a TXT file recording some of the arguments to this function
LD_u_axis_tick_spacing = 2;  % u-axis tick spacing and tick label spacing
LD_v_axis_tick_spacing = 2;  % v-axis tick spacing and tick label spacing
extra_title_margin = 0.5;  % extra vertical margin for plot title

% Calculate size so it is reported in specs later on
orig_size = size(img_in);

if (orig_size(1) ~= orig_size(2))
    warning('The input image to show_fft_plus is not square.  The function will not perform as expected.');
end

% Convert input mask/aperture to single to save memory
img_in = single(img_in);

% Create a figure showing the mask/aperture and save the figure to a file
if (show_aperture)
    plot_aperture(img_in, mask_name, filename_string, figure_num, font_size_const, nominal_plot_size, print_mode);
end

% Reduce dims of the mask/aperture so FFT uses less memory after padding
reduced = imresize(img_in, img_in_scale);
reduced_size = size(reduced);
fft_size = fft_scale * reduced_size;
clear img_in;  % frees up some memory

% Find characteristic FFT of this mask/aperture (not power spectrum yet)
xfm = fftshift(fft2(reduced, fft_size(1), fft_size(2)));

% Convolve the FFT with whatever pattern of stars, etc. we please
convmat = LD_to_convmat(LD, fft_scale);

% Note this is relative to xfm's scale...
%convmat = single(convmat);
xfm = conv2(xfm, convmat);

% Actually take the power spectrum and save the raw data therein to a file
xfm = abs(xfm) .^ 2;
%save([mask_name_alt ' raw PSF.mat'], 'xfm');  % This operation is long

% H = fspecial('Gaussian',[16 16], 6);
% xfm = imfilter(xfm,H);

% Take the log to roughly obtain a brightness
log_scaled = log10(xfm ./ max(max(xfm)));  % entries are nonpositive now 
ld_spans = (size(xfm) / fft_scale);
ld_bounds = (ld_spans ./ 2)' * [-1 1]; % the range of lambda/D shown over whole image

% Scale and crop the PSF manually to obtain a result without graph format
% We calculate the frame size to report it in the specs regardless of
% whether we actually display the simple PSF or not
frame_top =    round(1 + (size(xfm, 1) * (0.5 + 0.5 * LD_lim / ld_bounds(1, 1))));
frame_bottom = round(1 + (size(xfm, 1) * (0.5 + 0.5 * LD_lim / ld_bounds(1, 2))));
frame_left =   round(1 + (size(xfm, 2) * (0.5 + 0.5 * LD_lim / ld_bounds(2, 1))));
frame_right =  round(1 + (size(xfm, 2) * (0.5 + 0.5 * LD_lim / ld_bounds(2, 2))));
cropped_size = [frame_bottom - frame_top + 1, frame_right - frame_left + 1];
if (show_simple)
    cropped = log_scaled([frame_top:frame_bottom], [frame_left:frame_right]);
    cropped = (1/(mag_lims(2) - mag_lims(1))) * cropped + (mag_lims(2) / (mag_lims(2) - mag_lims(1)));
    figure(figure_num + 1);
    if print_mode
        cropped = imcomplement(cropped);  % this requires extra memory...
    end
    imshow(cropped);
    colormap(gray(256));
    imwrite(cropped, [filename_string ' simple PSF.png']);
end

% Use the automatic image scale/plot function so that axes are labeled
if (show_scaled)
    scaled_fig = figure(figure_num + 2);
    set(scaled_fig, 'Position', [0 0 nominal_plot_size]);
    imagesc(ld_bounds(1,:), ld_bounds(2,:), flipud(log_scaled));  % actually plot result; flip makes coords agree with convolution
    colormap(figure_num + 2, color_map);
    caxis([-mag_lims(2), -mag_lims(1)]);  % bound color axis
    h = colorbar;
    % bar.label.String = 'Base ten magnitude relative to max';
    ylabel(h, 'log_1_0 contrast');
    axis on;
    % these seem redundant, but performance consistent only with them all
    axis square;
    axis equal;
    xlim([-LD_lim, LD_lim]);
    ylim([-LD_lim, LD_lim]);
    set(gca, 'XTick', -LD_lim:LD_u_axis_tick_spacing:LD_lim);
    set(gca, 'YTick', -LD_lim:LD_v_axis_tick_spacing:LD_lim);
    set(gca, 'YDir', 'normal');
    set(gca, 'TickDir', 'out');  % draw ticks outside of PSF area
    xlabel('u [\lambda/D]');
    ylabel('v [\lambda/D]');
    my_title = title(['Ideal monochromatic, on-axis PSF of ' mask_name]);
    title_pos = get(my_title, 'Position');
    set(my_title, 'Position', title_pos + [0 extra_title_margin 0]);
    set(gca,'FontSize',font_size_const,'fontWeight','bold');
    set(h, 'FontSize', font_size_const, 'fontWeight', 'bold');  % color bar axis font
    set(findall(gcf,'type','text'),'FontSize',font_size_const,'fontWeight','bold');
    print('-depsc', '-painters', [filename_string ' PSF.eps']);
    print('-dpng', [filename_string ' PSF.png']);
end

if make_spec_file
    fid = fopen([filename_string ' PSF specs.txt'], 'w');
    fprintf(fid, ['original mask size:  ' num2str(orig_size(1)) ' px X ' num2str(orig_size(2)) ' px\r\n']);
    fprintf(fid, ['initial mask scaling:  ' num2str(img_in_scale) '\r\n']);
    fprintf(fid, ['reduced mask size:  ' num2str(reduced_size(1)) ' px X ' num2str(reduced_size(2)) ' px\r\n']);
    fprintf(fid, ['FFT domain scale:  ' num2str(fft_scale) '\r\n']);
    fprintf(fid, ['FFT size:  ' num2str(fft_size(1)) ' px X ' num2str(fft_size(2)) ' px\r\n']);
    fprintf(fid, ['asterism contents (u, v):  ']);
    
    for i=1:size(LD, 1)
        fprintf(fid, [num2str(LD(i, 3)) ' @ (' num2str(LD(i, 1)) ', ' num2str(LD(i, 2)) ') lam/D']);
        if i < size(LD, 1)
            fprintf(fid, '; ');
        end
    end
    fprintf(fid, '\r\n');
    fprintf(fid, ['magnitude limits:  [' num2str(-mag_lims(2)) ', ' num2str(-mag_lims(1)), ']\r\n']);
    fprintf(fid, ['lam/D limits:  [' num2str(-LD_lim) ', ' num2str(LD_lim) ']\r\n']);
    fprintf(fid, ['output PSF size:  ' num2str(cropped_size(1)) ' px X ' num2str(cropped_size(2)) ' px\r\n']);
    fprintf(fid, ['nominal plot size:  ' num2str(nominal_plot_size(1)) ' px X ' num2str(nominal_plot_size(2)) ' px\r\n']);
    fprintf(fid, ['timestamp:  ' datestr(now)]);
    fclose(fid);
end

end